[env]
DO_NOT_TRACK = "1"

[tools]
bun = "latest"

[hooks]
postinstall = '''
  cd my-react-router-app && test -d node_modules || bun install
'''

[tasks.docker]
description = "Build and start the Docker container"
dir = "."
run = "docker compose -f compose.yaml up --build"

[settings]
experimental = true

[settings.npm]
package_manager = "bun"
